"""baseline schema

Revision ID: d906cdd1b7ee
Revises: 
Create Date: 2026-09-16 13:57:23.110448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd906cdd1b7ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('cars', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('cars', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('cars_user_id_fkey', 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mechanics', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mechanics', 'access_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mechanics', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_constraint('mechanics_phone_key', 'mechanics', type_='unique')
    op.create_index(op.f('ix_mechanics_phone'), 'mechanics', ['phone'], unique=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('messages_booking_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'bookings', ['booking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('services', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.alter_column('services', 'price',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_booking_id_fkey', 'messages', 'bookings', ['booking_id'], ['id'])
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_mechanics_phone'), table_name='mechanics')
    op.create_unique_constraint('mechanics_phone_key', 'mechanics', ['phone'])
    op.alter_column('mechanics', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('mechanics', 'access_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mechanics', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key('cars_user_id_fkey', 'cars', 'users', ['user_id'], ['id'])
    op.alter_column('cars', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('cars', 'created_at')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'])
    op.alter_column('bookings', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
